version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

image:
  - Visual Studio 2019
  - Ubuntu

stack: node 14, jdk 15, python 3.9 x64

install:
  - cmd: "SET JAVA_HOME=C:\\Program Files\\Java\\jdk15"
  - cmd: "SET PATH=%JAVA_HOME%\\bin;%path%"
  - cmd: "SET PYTHON3=C:\\Python39-x64"
  - cmd: "SET PATH=%PYTHON3%;%PYTHON3%\\Scripts;%path%"
  - cmd: java -version
  - cmd: python --version"
  - cmd: python -m pip install -r requirements.txt
  - sh: java -version
  - sh: whereis python3.9
  - sh: . /home/appveyor/venv3.9/bin/activate
  - sh: python --version
  - sh: pip install -r requirements.txt

build_script:
  - cmd: .\gradlew.bat build
  - sh: bash ./gradlew build

test_script:
  - cmd: .\gradlew.bat test jacocoJupTestReport
  - cmd: coverage-3.9 run scripts\\run_unit_tests.py
  - sh: bash ./gradlew test jacocoJupTestReport
  - sh: coverage-3.9 run scripts/run_unit_tests.py

after_test:
  - cmd: python scripts\\create_problems_list.py
  - sh: python3.9 scripts/create_problems_list.py
