name: Workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.0.1"
          architecture: x64
      - run: java -version
      - name: Make
        working-directory: ./
        run: sudo make javacode
