name: Workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.0.1"
          architecture: x64
      - run: java -version
      - name: Make javacode
        run: make javacode
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"
      - run: python --version
      - run: pip install -r requirements.txt
      - name: Make pythoncode
        run: make pythoncode
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.2.103"
      - run: dotnet --version
      - name: Make csharpcode
        run: make csharpcode
